package com.ibanity.apis.client.services;

import com.ibanity.apis.client.exceptions.ResourceNotFoundException;
import com.ibanity.apis.client.models.CustomerAccessToken;
import com.ibanity.apis.client.models.PaymentInitiationRequest;

import java.util.UUID;

/**
 * Service for Payments related APIs
 */
public interface PaymentsInitiationService {
    /**
     * Initiate/create a payment request towards the provided financial institution
     * @param paymentInitiationRequest the payment request that will be submitted to the financial institution
     * @param customerAccessToken the token generated by the call to the corresponding service (See @link com.ibanity.services.CustomerAccessTokenService#createCustomerAccessToken(CustomerAccessToken)}
     * @return a payment initiation request details
     */
    PaymentInitiationRequest initiatePaymentRequest(CustomerAccessToken customerAccessToken, PaymentInitiationRequest paymentInitiationRequest);

    /**
     * Provide the
     * @param financialInstitutionId the id of the financial institution
     * @param paymentInitiationRequestId the id of the payment initiation request that we need the details about
     * @param customerAccessToken the token generated by the call to the corresponding service (See @link com.ibanity.services.CustomerAccessTokenService#createCustomerAccessToken(CustomerAccessToken)}
     * @return the payment initiation request details
     * @throws ResourceNotFoundException when the provided ID is not known
     */
    PaymentInitiationRequest getPaymentInitiationRequest(CustomerAccessToken customerAccessToken, UUID financialInstitutionId, UUID paymentInitiationRequestId) throws ResourceNotFoundException;

}
