package com.ibanity.api;

import com.ibanity.models.Account;
import com.ibanity.models.AccountInformationAccessAuthorization;
import com.ibanity.models.AccountInformationAccessRequest;
import com.ibanity.models.CustomerAccessToken;

import java.util.List;
import java.util.UUID;

/**
 * Service for Accounts related APIs
 */
public interface AccountsService {

    /**
     * Get ALL customer accounts (from all authorized financial institutions)
     * note: In an account object's, the financialInstitution property object, only the financialInstitution.id is populated
     * @param customerAccessToken the token generated by the call to the corresponding service (See @link com.ibanity.api.CustomerAccessTokenService#createCustomerAccessToken(CustomerAccessToken)}
     * @return list of all customer's accounts
     */
    List<Account> getCustomerAccounts(CustomerAccessToken customerAccessToken);

    /**
     * Get customer's accounts from a particular financial institution
     * note: In an account object's, the financialInstitution property object, only the financialInstitution.id is populated
     * @param customerAccessToken the token generated by the call to the corresponding service (See @link com.ibanity.api.CustomerAccessTokenService#createCustomerAccessToken(CustomerAccessToken)}
     * @param financialInstitutionId the Id of the financial institution to be used
     * @return list of customer's accounts in the specified financial institution
     */
    List<Account> getCustomerAccounts(CustomerAccessToken customerAccessToken, UUID financialInstitutionId);

    /**
     * Provide the URL to be redirected to the PSU (end-user) Web Browser.
     * The Redirect URL will redirect the end-user to the Financial Institution in order to authorize iBanity to access the selected bank accounts
     * @param customerAccessToken the token generated by the call to the corresponding service (See @link com.ibanity.api.CustomerAccessTokenService#createCustomerAccessToken(CustomerAccessToken)}
     * @param financialInstitutionId The Id of the Financial Institution for which the account access will be requested
     * @param accountInformationAccessRequest Information related to the request:
     *                                        redirect URI : to redirect the end-user to the TPP page after the authorization flow has been completed, this URI needs to be a URI referenced in the iBanity Portal
     *                                        consentReference: the consent reference
     * @return an accountInformationAccessRequest containing a redirect URI (property: links.redirect) to be provided, as redirect response, to the end-user browser
     */
    AccountInformationAccessRequest getAccountInformationAccessRedirectUrl(CustomerAccessToken customerAccessToken, UUID financialInstitutionId, AccountInformationAccessRequest accountInformationAccessRequest);

    /**
     * Get the list of Account Access Authorizations
     * @param customerAccessToken the token generated by the call to the corresponding service (See @link com.ibanity.api.CustomerAccessTokenService#createCustomerAccessToken(CustomerAccessToken)}
     * @param financialInstitutionId The Id of the Financial Institution for which the accounts access was requested
     * @param accountInformationAccessRequestId The Id of the Account Information Access Request through which the access was requested originally
     * @return the list of authorizations details
     */
    List<AccountInformationAccessAuthorization> getAccountInformationAccessAuthorizations(CustomerAccessToken customerAccessToken, UUID financialInstitutionId, UUID accountInformationAccessRequestId);

    /**
     * Remove an Account Access Authorization
     * @param customerAccessToken the token generated by the call to the corresponding service (See @link com.ibanity.api.CustomerAccessTokenService#createCustomerAccessToken(CustomerAccessToken)}
     * @param financialInstitutionId The Id of the Financial Institution for which the accounts access was requested
     * @param accountInformationAccessRequestId The Id of the Account Information Access Request through which the access was requested originally
     * @param accountInformationAccessAuthorizationId The Id of the Account Information Access Authorization that we want to remove
     */
    void removeAccountAccess(CustomerAccessToken customerAccessToken, UUID financialInstitutionId, UUID accountInformationAccessRequestId, UUID accountInformationAccessAuthorizationId);
}
