package com.ibanity.api;

import com.ibanity.models.Account;
import com.ibanity.models.CustomerAccessToken;

import java.util.List;
import java.util.UUID;

/**
 * Service for Accounts related APIs
 */
public interface AccountsService {

    /**
     * Get ALL customer accounts (from all authorized financial institutions)
     * note: In account objects's financialInstitution property object, only the financialInstitution.id is populated
     * @param customerAccessToken the token generated by the call to the corresponding service (See @link com.ibanity.api.CustomerAccessTokenService#createCustomerAccessToken(CustomerAccessToken)}
     * @return list of all customer's accounts
     */
    List<Account> getCustomerAccounts(CustomerAccessToken customerAccessToken);

    /**
     * Get customer's accounts from a particular financial institution
     * note: In account objects's financialInstitution property object, only the financialInstitution.id is populated
     * @param customerAccessToken the token generated by the call to the corresponding service (See @link com.ibanity.api.CustomerAccessTokenService#createCustomerAccessToken(CustomerAccessToken)}
     * @param financialInstitutionId the financial institution ID
     * @return list of customer's accounts in the specified financial institution
     */
    List<Account> getCustomerAccounts(CustomerAccessToken customerAccessToken, UUID financialInstitutionId);
}
